=== gengfo/ARPTest/ArpAppTest/src/test/resources/jmsProviderConfigProject.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:complexType name="connection-factoryType">
		<xs:sequence>
			<xs:element ref="local-jndi-name"/>
			<xs:element ref="remote-jndi-name"/>
			<xs:element ref="username"/>
			<xs:element ref="password"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="jms-providerType">
		<xs:sequence>
			<xs:element ref="name"/>
			<xs:element ref="initial-context-factory"/>
			<xs:element ref="provider-url"/>
			<xs:element ref="security-principal"/>
			<xs:element ref="security-credentials"/>
			<xs:element name="connection-factory" type="connection-factoryType" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="jms-provider-config">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="jms-providers">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="jms-provider" type="jms-providerType" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="connection-pool">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="max-active" type="xs:integer" default="8" minOccurs="0"/>
							<xs:element name="max-wait" type="xs:integer" default="25000" minOccurs="0"/>
							<xs:element name="max-idle" type="xs:integer" default="8" minOccurs="0"/>
							<xs:element name="max-total" type="xs:integer" default="-1" minOccurs="0"/>
							<xs:element name="min-idle" type="xs:integer" default="0" minOccurs="0"/>
							<xs:element name="clean-interval" type="xs:integer" default="-1" minOccurs="0"/>
							<xs:element name="idle-time" type="xs:integer" default="1800000" minOccurs="0"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="name" type="xs:string"/>
	<xs:element name="initial-context-factory" type="xs:string"/>
	<xs:element name="provider-url" type="xs:string"/>
	<xs:element name="security-credentials" type="xs:string"/>
	<xs:element name="security-principal" type="xs:string"/>
	<xs:element name="remote-jndi-name" type="xs:string"/>
	<xs:element name="local-jndi-name" type="xs:string"/>
	<xs:element name="username" type="xs:string"/>
	<xs:element name="password" type="xs:string"/>
</xs:schema>

=== gengfo/ARPTest/ArpAppTest/src/test/resources/jmsProviderConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<jms-provider-config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="jmsProviderConfigProject.xsd">
	<jms-providers>
		<jms-provider>
			<name></name>
			<initial-context-factory>com.tibco.tibjms.naming.TibjmsInitialContextFactory</initial-context-factory>
			<provider-url>tcp://shasun3:7223</provider-url>
			<security-principal>arpuser</security-principal>
			<security-credentials>arpuser</security-credentials>
			<connection-factory>
				<local-jndi-name>MessageFrameworkXAPoolCF</local-jndi-name>
				<remote-jndi-name>XAGenericConnectionFactory</remote-jndi-name>
				<username>arpuser</username>
				<password>arpuser</password>
			</connection-factory>
			<connection-factory>
				<local-jndi-name>MessageFrameworkPoolCF</local-jndi-name>
				<remote-jndi-name>GenericConnectionFactory</remote-jndi-name>
				<username>arpuser</username>
				<password>arpuser</password>
			</connection-factory>
		</jms-provider>
		
		<jms-provider>
			<name>CLIENTPUSH</name>
			<initial-context-factory>com.tibco.tibjms.naming.TibjmsInitialContextFactory</initial-context-factory>
			<provider-url>tcp://cdremsint1:7554,tcp://cdremsint2:7554</provider-url>
			<security-principal>fwk_cpfw</security-principal>
			<security-credentials>fwk_cpfw</security-credentials>
			<connection-factory>
				<local-jndi-name>MessageFrameworkXAPoolCF</local-jndi-name>
				<remote-jndi-name>XAGenericConnectionFactory</remote-jndi-name>
				<username>fwk_cpfw</username>
				<password>fwk_cpfw</password>
			</connection-factory>
			<connection-factory>
				<local-jndi-name>MessageFrameworkPoolCF</local-jndi-name>
				<remote-jndi-name>GenericConnectionFactory</remote-jndi-name>
				<username>fwk_cpfw</username>
				<password>fwk_cpfw</password>
			</connection-factory>
		</jms-provider>
		
		<jms-provider>
			<name>FODE</name>
			<initial-context-factory>com.tibco.tibjms.naming.TibjmsInitialContextFactory</initial-context-factory>
			<provider-url>tcp://choica3-vista:7222</provider-url>
			<security-principal>fwk_fode</security-principal>
			<security-credentials>fwk_fode</security-credentials>
			<connection-factory>
				<local-jndi-name>MessageFrameworkXAPoolCF</local-jndi-name>
				<remote-jndi-name>XAGenericConnectionFactory</remote-jndi-name>
				<username>fwk_fode</username>
				<password>fwk_fode</password>
			</connection-factory>
			<connection-factory>
				<local-jndi-name>MessageFrameworkPoolCF</local-jndi-name>
				<remote-jndi-name>GenericConnectionFactory</remote-jndi-name>
				<username>fwk_fode</username>
				<password>fwk_fode</password>
			</connection-factory>
		</jms-provider>
		
	</jms-providers>
	<connection-pool>
		<max-active>300</max-active>
		<max-wait>600000</max-wait>
		<max-idle></max-idle>
		<max-total></max-total>
		<min-idle></min-idle>
		<clean-interval></clean-interval>
		<idle-time></idle-time>
	</connection-pool>
</jms-provider-config>
